# Site settings
author: Joanna Kalema 
title: Joanna Chronicles
header-img: img/home-bg.png
email: kalemajoanna@gmail.com
copyright_name: Joanna Kalema 
description: > # this means to ignore newlines until "baseurl:"
  The journey of Joanna's coding journey in words not code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jokale

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
